# Force new deploy - [huidige datum/tijd]
# Basis configuratie
[build]
  publish = "/"

# 404 configuratie
[[redirects]]
  force = true
  from = "/*"
  status = 404
  to = "/404.html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
